Traceback (most recent call last):
  File "/nix/store/qrkgxqbbr00qjik2rfqdw3z8a062s3ls-python3.8-jupyter-cache-0.4.2/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/nix/store/ria264d36cmhxik90bmzwi12s7nll1y3-python3.8-nbclient-0.5.3/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/nix/store/ria264d36cmhxik90bmzwi12s7nll1y3-python3.8-nbclient-0.5.3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/nix/store/ria264d36cmhxik90bmzwi12s7nll1y3-python3.8-nbclient-0.5.3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/nix/store/4s0h5aawbap3xhldxhcijvl26751qrjr-python3-3.8.9/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/nix/store/ria264d36cmhxik90bmzwi12s7nll1y3-python3.8-nbclient-0.5.3/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/nix/store/ria264d36cmhxik90bmzwi12s7nll1y3-python3.8-nbclient-0.5.3/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/nix/store/ria264d36cmhxik90bmzwi12s7nll1y3-python3.8-nbclient-0.5.3/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import babypandas as bpd
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(456)
heads_probability = np.random.random()

sample = bpd.DataFrame().assign(
    trial=np.arange(1,100+1),
    outcome=np.random.choice(
        ['Heads', 'Tails'],
        p=[heads_probability, 1-heads_probability],
        size=100
    )
)

sample_props = sample.groupby('outcome').count().get('trial') / 100
sample_props.plot(kind='bar')

plt.axhline(y=0.5, c='k', linestyle='dashed')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-129bf074a68f>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mimport[0m [0mbabypandas[0m [0;32mas[0m [0mbpd[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;32mimport[0m [0mnumpy[0m [0;32mas[0m [0mnp[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0;32mimport[0m [0mmatplotlib[0m[0;34m.[0m[0mpyplot[0m [0;32mas[0m [0mplt[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0mnp[0m[0;34m.[0m[0mrandom[0m[0;34m.[0m[0mseed[0m[0;34m([0m[0;36m456[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'matplotlib'
ModuleNotFoundError: No module named 'matplotlib'

